version: '2'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-8-0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD= yes
    ports:
      - 8002:3306
  website:
    container_name: php-7-4
    image: php_img:latest
    build:
      context: ./
    volumes:
      - ./code:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 8001:80
    depends_on:
      - mysql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: php-myadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
