version: '2'
services:
  dpe-mysql:
    image: mysql:8.0
    container_name: dpe-mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD= yes
    ports:
      - 18002:3306
  dpe-website:
    container_name: dpe-website
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./code:/var/www/html/
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 18001:80
    depends_on:
      - dpe-mysql
  dpe-phpmyadmin:
    depends_on:
      - dpe-mysql
    image: phpmyadmin/phpmyadmin
    container_name: dpe-phpmyadmin
    ports:
      - 18003:80
    environment:
      PMA_HOST: dpe-mysql
