version: '2'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD= yes
    ports:
      - 8002:3306
  website:
    container_name: php74
    image: php_img:latest
    build:
      context: ./
    volumes:
      - C:\path\to\php\code:/var/www/html/
    ports:
      - 8001:80
    depends_on:
      - mysql
